### ISSUE TITLE
Typo on line 120

### ISSUE THREAD

**Issue by ghost** [veerendra2/funmotd#2]
Should be `hospital`
This is shown in the README.
https://github.com/veerendra2/funmotd/blob/6d59473608af5ab9ffd224ea794bab1ee3ec8734/funmotd/quotes_db.py#L120

**Comment by veerendra2** [comment]
Thanks for creating the issue. Fixed https://github.com/veerendra2/funmotd/commit/bf1287d4071a65c9a2721a74157d497fe6956b47
